// 墨水屏尺寸 250 x 128，实际可见 250 x 122

#define SCREEN_WIDTH 250
#define SCREEN_HEIGHT 128
#define SCREEN_PADDING 10

#define ICON_STATUS_SIZE 24
#define ICON_MARGIN 5

#define ICON_BLE_X SCREEN_WIDTH - ICON_STATUS_SIZE - SCREEN_PADDING
#define ICON_BLE_Y SCREEN_PADDING

#define ICON_WIFI_X SCREEN_WIDTH - ICON_STATUS_SIZE - SCREEN_PADDING
#define ICON_WIFI_Y ICON_BLE_Y + ICON_STATUS_SIZE + ICON_MARGIN

#define COMPONENT_TIME_X SCREEN_PADDING
#define COMPONENT_TIME_Y 45

#define COMPONENT_DATE_X SCREEN_PADDING
#define COMPONENT_DATE_Y 75

#define COMPONENT_WEEKDAY_X SCREEN_PADDING
#define COMPONENT_WEEKDAY_Y 95