#define ICON_STATUS_SIZE 24

#define ICON_BLE_X 180
#define ICON_BLE_Y 15

#define ICON_WIFI_X 210
#define ICON_WIFI_Y 15

#define COMPONENT_TIME_X 15
#define COMPONENT_TIME_Y 45

#define COMPONENT_DATE_X 15
#define COMPONENT_DATE_Y 75

#define COMPONENT_WEEKDAY_X 15
#define COMPONENT_WEEKDAY_Y 95